name: Deploy Learning Material

on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build Documentation
        run: |
          xcodebuild docbuild\
            -workspace LearningMaterial\
            -scheme LearningMaterial\
            -destination 'generic/platform=iOS'\
            -derivedDataPath ../DerivedData
      - name: Process Archive
        run: |
          mkdir _site
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting ../DerivedData/Build/Products/Debug-iphoneos/LearningMaterial.doccarchive\
            --output-path _site \
            --hosting-base-path /BuildABuddyKit/
      - name: Create Custom index.html
        run: |
          rm _site/index.html
          cat > _site/index.html <<- EOM
          <!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url='https://simonbs.github.io/BuildABuddyKit/tutorials/table-of-contents'" />
            </head>
           <body>
              <p>Please follow <a href="https://simonbs.github.io/BuildABuddyKit/tutorials/table-of-contents">this link</a>.</p>
            </body>
          </html>
          EOM
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
